import { CardData } from './types';

export interface DeckCardEntry {
  code: string;
  qty: number;
  card?: CardData;
}

export interface ParsedDeckData {
  isValid: boolean;
  isDeckBuilderCode: boolean;
  mainDeck: DeckCardEntry[];
  sideDeck: DeckCardEntry[];
  totalMainCount: number;
  totalSideCount: number;
  totalCount: number;
  rawDeckBuilderCode: string;
  missingCodes: string[];
}

const normalizeCode = (val: string | undefined | null) => 
  (val ? String(val) : '').replace(/[^a-zA-Z0-9]/g, '').toLowerCase();

/**
 * Parses deck codes from either:
 * 1. Base64 encoded string generated by the Deck Builder: btoa(JSON.stringify({ main: string[], side: string[] }))
 * 2. Raw JSON string: { main: [...], side: [...] } or [...]
 * 3. Comma/newline separated codes with optional multipliers: "3x 2026/0001/00301, 2025/0001/00001"
 */
export function parseDeckFromCode(rawInput: string | undefined | null, allCards?: CardData[]): ParsedDeckData {
  const emptyResult: ParsedDeckData = {
    isValid: false,
    isDeckBuilderCode: false,
    mainDeck: [],
    sideDeck: [],
    totalMainCount: 0,
    totalSideCount: 0,
    totalCount: 0,
    rawDeckBuilderCode: '',
    missingCodes: []
  };

  if (!rawInput || typeof rawInput !== 'string') return emptyResult;
  const trimmed = rawInput.trim();
  if (!trimmed) return emptyResult;

  const cardsList = Array.isArray(allCards) ? allCards : [];

  let parsedJson: any = null;
  let isDeckBuilderCode = false;

  // 1. Try Base64 decoding (standard Deck Builder format)
  try {
    const decoded = atob(trimmed);
    parsedJson = JSON.parse(decoded);
    isDeckBuilderCode = true;
  } catch {
    // 2. Try direct JSON parsing
    try {
      parsedJson = JSON.parse(trimmed);
      isDeckBuilderCode = true;
    } catch {
      parsedJson = null;
    }
  }

  const findCard = (code: string | undefined | null): CardData | undefined => {
    if (!code) return undefined;
    const safeCode = String(code).trim();
    if (!safeCode) return undefined;
    const safeCodeLower = safeCode.toLowerCase();
    const normalizedTarget = normalizeCode(safeCode);

    return cardsList.find(c => {
      if (!c) return false;
      const cCode = c.code ? String(c.code).trim() : '';
      const cName = c.name ? String(c.name).trim() : '';
      return (
        (cCode !== '' && cCode === safeCode) || 
        (cCode !== '' && normalizeCode(cCode) === normalizedTarget) ||
        (cName !== '' && cName.toLowerCase() === safeCodeLower)
      );
    });
  };

  const groupCodes = (codes: (string | undefined | null)[]): { entries: DeckCardEntry[]; missing: string[] } => {
    const counts = new Map<string, number>();
    const originalCodes = new Map<string, string>();

    for (const rawC of codes) {
      if (!rawC) continue;
      const c = String(rawC).trim();
      if (!c) continue;
      const key = normalizeCode(c);
      counts.set(key, (counts.get(key) || 0) + 1);
      if (!originalCodes.has(key)) {
        originalCodes.set(key, c);
      }
    }

    const entries: DeckCardEntry[] = [];
    const missing: string[] = [];

    for (const [key, qty] of counts.entries()) {
      const orig = originalCodes.get(key) || key;
      const card = findCard(orig);
      if (!card) {
        missing.push(orig);
      }
      entries.push({
        code: card && card.code ? card.code : orig,
        qty,
        card
      });
    }

    return { entries, missing };
  };

  // If successfully parsed from Deck Builder JSON/Base64
  if (parsedJson && (typeof parsedJson === 'object')) {
    let mainCodesRaw: string[] = [];
    let sideCodesRaw: string[] = [];

    if (Array.isArray(parsedJson)) {
      mainCodesRaw = parsedJson;
    } else {
      if (Array.isArray(parsedJson.main)) mainCodesRaw = parsedJson.main;
      if (Array.isArray(parsedJson.side)) sideCodesRaw = parsedJson.side;
    }

    const { entries: mainDeck, missing: missingMain } = groupCodes(mainCodesRaw);
    const { entries: sideDeck, missing: missingSide } = groupCodes(sideCodesRaw);

    const totalMainCount = mainCodesRaw.length;
    const totalSideCount = sideCodesRaw.length;

    // Ensure rawDeckBuilderCode is clean Base64
    let rawDeckBuilderCode = trimmed;
    try {
      rawDeckBuilderCode = btoa(JSON.stringify({ main: mainCodesRaw, side: sideCodesRaw }));
    } catch {
      rawDeckBuilderCode = trimmed;
    }

    return {
      isValid: mainDeck.length > 0 || sideDeck.length > 0,
      isDeckBuilderCode: true,
      mainDeck,
      sideDeck,
      totalMainCount,
      totalSideCount,
      totalCount: totalMainCount + totalSideCount,
      rawDeckBuilderCode,
      missingCodes: [...missingMain, ...missingSide]
    };
  }

  // 3. Fallback: Parse line-by-line or comma-separated list
  const rawEntries = trimmed
    .split(/[,\n]/)
    .map(entry => entry.trim())
    .filter(Boolean);

  const flatMainCodes: string[] = [];
  const entries: DeckCardEntry[] = [];
  const missing: string[] = [];

  for (const entry of rawEntries) {
    const match = entry.match(/^(\d+)\s*[xX]?\s+(.+)$/);
    let qty = 1;
    let codeRaw = entry;
    if (match) {
      qty = parseInt(match[1], 10) || 1;
      codeRaw = match[2].trim();
    }

    const card = findCard(codeRaw);
    const finalCode = card && card.code ? card.code : codeRaw;
    if (!card) {
      missing.push(codeRaw);
    }

    for (let i = 0; i < qty; i++) {
      flatMainCodes.push(finalCode);
    }

    entries.push({
      code: finalCode,
      qty,
      card
    });
  }

  let generatedBase64 = '';
  try {
    generatedBase64 = btoa(JSON.stringify({ main: flatMainCodes, side: [] }));
  } catch {
    generatedBase64 = '';
  }

  return {
    isValid: entries.length > 0,
    isDeckBuilderCode: false,
    mainDeck: entries,
    sideDeck: [],
    totalMainCount: flatMainCodes.length,
    totalSideCount: 0,
    totalCount: flatMainCodes.length,
    rawDeckBuilderCode: generatedBase64,
    missingCodes: missing
  };
}

/**
 * Helper to parse a code segment into prefix and numeric value for natural sorting.
 * Handles standard numbers ("00001" -> 1), booster/promo variants ("B0001" -> prefix "B", num 1, "0B188" -> prefix "B", num 188),
 * and general alphanumeric formats ("BIC-01" -> prefix "BIC", num 1).
 */
function parseCodeSegment(seg: string): { prefix: string; num: number | null; raw: string } {
  const s = seg.trim();
  if (/^\d+$/.test(s)) {
    return { prefix: "", num: parseInt(s, 10), raw: s };
  }
  const matchB = s.match(/^0?([a-zA-Z]+)(\d+)$/);
  if (matchB) {
    return { prefix: matchB[1].toUpperCase(), num: parseInt(matchB[2], 10), raw: s };
  }
  const matchGen = s.match(/^([a-zA-Z\-_]*?)(\d+)$/);
  if (matchGen) {
    return { prefix: matchGen[1].toUpperCase(), num: parseInt(matchGen[2], 10), raw: s };
  }
  return { prefix: s.toUpperCase(), num: null, raw: s };
}

function compareSegments(segA: string, segB: string): number {
  const pA = parseCodeSegment(segA);
  const pB = parseCodeSegment(segB);

  // Standard pure numbers (empty prefix) come before letter-prefixed cards
  if (pA.prefix !== pB.prefix) {
    if (pA.prefix === "") return -1;
    if (pB.prefix === "") return 1;
    const prefCmp = pA.prefix.localeCompare(pB.prefix, undefined, { sensitivity: 'base' });
    if (prefCmp !== 0) return prefCmp;
  }

  if (pA.num !== null && pB.num !== null) {
    if (pA.num !== pB.num) return pA.num - pB.num;
  }

  return segA.localeCompare(segB, undefined, { numeric: true, sensitivity: 'base' });
}

/**
 * Robust natural/numerical sorting comparison for card codes.
 * Ensures cards are ordered by set and numeric index (e.g. 00001, 00002, 00010, 0011, 00100).
 */
export function compareCardCodes(codeA?: string | null, codeB?: string | null): number {
  if (!codeA && !codeB) return 0;
  if (!codeA) return 1;
  if (!codeB) return -1;

  const trimA = String(codeA).trim();
  const trimB = String(codeB).trim();

  if (trimA === trimB) return 0;

  const partsA = trimA.split('/');
  const partsB = trimB.split('/');

  if (partsA.length === partsB.length && partsA.length > 1) {
    for (let i = 0; i < partsA.length; i++) {
      const cmp = compareSegments(partsA[i], partsB[i]);
      if (cmp !== 0) return cmp;
    }
    return 0;
  }

  return compareSegments(trimA, trimB);
}
