import { CardData } from "./types";

export const invasaoDoCaosCards: CardData[] = [
  {
    "name": "Mahina - O Arauto do Véu",
    "rarity": "Beta",
    "type": "Herói",
    "archetype": "Véu",
    "collection": "Invasão do Caos",
    "ct": 11,
    "attack": 1,
    "defense": 1,
    "description": "Para invocar este Herói, descarte um Herói com «Mahina» em seu nome do campo para a Zona Apagada ou tenha 4 cartas com «Véu» em seu nome ou Arquétipo em seu lado do campo.\n\nEste Herói não pode deixar o campo por resultado de combate, em vez disso ele recebe um Arquétipo a sua escolha.\n\nNo começo do turno, este Herói recebe 5 de Ataque.\n\nA qualquer momento, descarte uma carta com «Véu» em seu nome ou Arquétipo do seu lado campo para a Zona Apagada para negar uma carta usada.\n\nNo começo do turno, caso queira, selecione uma carta com «Véu» ou «Camada» em seu nome ou um combatente com Arquétipo Véu de suas Zonas e adicione a sua mão.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736620932_Prancheta%2014.png?alt=media&token=efac4eed-1323-40d1-a15c-9687c910a9b2",
    "code": "2026/0001/00301",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Arthemiel do Véu",
    "rarity": "Beta",
    "type": "Combatente",
    "archetype": "Véu",
    "collection": "Invasão do Caos",
    "ct": 9,
    "attack": 10,
    "defense": 15,
    "description": "O CT deste combatente é reduzido em 4 caso o Herói «Mahina - O Arauto do Véu» esteja em campo.\n\nNo começo da rodada, receba 7 de Vida de Jogador.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736640296_Prancheta%2024.png?alt=media&token=aadd5a29-3fe7-4782-a975-03b4600fe18c",
    "code": "2026/0001/00302",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Atropos do Véu",
    "rarity": "Beta",
    "type": "Combatente",
    "archetype": "Véu",
    "collection": "Invasão do Caos",
    "ct": 6,
    "attack": 6,
    "defense": 5,
    "description": "O CT deste combatente é reduzido em 4 caso o Herói «Mahina - O Arauto do Véu» esteja em campo.\n\nNo começo da rodada, cause 5 de dano na Vida do Jogador inimigo.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736659574_Prancheta%2034.png?alt=media&token=030a2ea9-f434-4997-b6d4-8cc7d0242f0e",
    "code": "2026/0001/00303",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Eizen do Véu",
    "rarity": "Beta",
    "type": "Combatente",
    "archetype": "Véu",
    "collection": "Invasão do Caos",
    "ct": 9,
    "attack": 7,
    "defense": 7,
    "description": "O CT deste combatente é reduzido em 4 caso o Herói «Mahina - O Arauto do Véu» esteja em campo. No começo da rodada, invoque de qualquer lugar, um combatente não Herói com «Véu» em seu nome ou Arquétipo Véu.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736691154_Prancheta%2044.png?alt=media&token=a76855ae-ef51-427c-9b58-129543899e11",
    "code": "2026/0001/00304",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Três do Véu",
    "rarity": "Beta",
    "type": "Combatente",
    "archetype": "Véu",
    "collection": "Invasão do Caos",
    "ct": 6,
    "attack": 9,
    "defense": 9,
    "description": "O CT deste combatente é reduzido em 4 caso o Herói «Mahina - O Arauto do Véu» esteja em campo.\n\nNo começo da rodada, role 3 dados D6, caso saia 3 em qualquer um dos dados, cause 3 de Dano Primordial no Deck inimigo ou retorne uma carta do campo para o Deck de seu dono.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736708668_Prancheta%2054.png?alt=media&token=c7864a36-a5a2-4572-a495-d919adeedda8",
    "code": "2026/0001/00305",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Crystal Caótica do Véu",
    "rarity": "Beta",
    "type": "Combatente",
    "archetype": "Véu / Furtivo / Insano / Sortudo",
    "collection": "Invasão do Caos",
    "ct": 12,
    "attack": 2,
    "defense": 15,
    "description": "O CT deste combatente é reduzido em 4 caso um Herói com «Véu» em seu nome esteja em campo.\n\nEnquanto este combatente estiver em campo, o ataque e vida de todos os combatentes inimigos são invertidos (caso a vida se torne 0, ele é enviado para a Zona Morta).\n\nEste combatente recebe 5 de ataque para cada carta no campo inimigo.\n\nSe alguma carta com «Jim» ou «Mahina» em seu nome estiver do seu lado do campo, «Crystal Caótica do Véu» ataca duas vezes por turno.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736725588_Prancheta%2064.png?alt=media&token=40f7e987-e487-4dea-a6a5-bbfb274a7944",
    "code": "2026/0001/00306",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Zwey",
    "rarity": "Beta",
    "type": "Combatente",
    "archetype": "Cósmico / Véu",
    "collection": "Invasão do Caos",
    "ct": 6,
    "attack": 5,
    "defense": 10,
    "description": "O CT deste combatente é reduzido em 4 caso um Herói com «Véu» em seu nome esteja em campo.\n\nA qualquer momento, uma vez por rodada, reduza o ataque de outro combatente (não Herói) para zero.\n\nPara cada combatente com zero de ataque em campo, no começo do turno, receba 3 de mana.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736768114_Prancheta%2074.png?alt=media&token=e6174e4a-4be8-4c08-8a62-96bf2330599e",
    "code": "2026/0001/00307",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "LUNALLY",
    "rarity": "Beta",
    "type": "Combatente",
    "archetype": "Véu",
    "collection": "Invasão do Caos",
    "ct": 4,
    "attack": 5,
    "defense": 3,
    "description": "O CT deste combatente é reduzido em 4 caso um Herói com «Véu» em seu nome esteja em campo.\n\nEnquanto esta carta estiver em campo, a primeira carta na rodada que qualquer jogador usar como reação a uma ação custa o dobro de recursos.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736779698_Prancheta%2084.png?alt=media&token=2fc88326-3dc0-4716-b72a-c61ae3e9aae0",
    "code": "2026/0001/00308",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "RYURAN",
    "rarity": "Beta",
    "type": "Combatente",
    "archetype": "Véu / Cósmico / Furtivo",
    "collection": "Invasão do Caos",
    "ct": 1,
    "attack": 1,
    "defense": 7,
    "description": "Para cada combatente com Arquétipo Véu do seu lado do campo ou suas Zonas, «Ryuran» recebe 3 de ataque.\n\nApós 3 rodadas em campo, a qualquer momento, descarte «Ryuran» para a Zona Apagada e invoque outro combatente com Arquétipo Véu de qualquer Zona.\n\nNo começo da rodada, envie «Ryuran» da sua Zona Apagada para Zona Morta e invoque um combatente com «Serviçal» em seu nome.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736791432_Prancheta%2094.png?alt=media&token=10ae125f-60d4-45e6-9725-cdf39a382655",
    "code": "2026/0001/00309",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Aqua Caótica",
    "rarity": "Beta",
    "type": "Combatente",
    "archetype": "Véu / Divindade",
    "collection": "Invasão do Caos",
    "ct": 7,
    "attack": 0,
    "defense": 13,
    "description": "O CT deste combatente é reduzido em 4 caso o Herói «Mahina - O Arauto do Véu» esteja em campo.<br><br>«Aqua Caótica» pode receber ataques de seu próprio lado do campo, o combatente inimigo na Área a frente dela recebe o dobro de dano que ela receber (ignorando arquétipos).",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736801198_Prancheta%20104.png?alt=media&token=ef52abd8-a8cd-477e-b127-2c3ec2fbbf7d",
    "code": "2026/0001/00310",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Rebirth do Véu",
    "rarity": "Beta",
    "type": "Combatente",
    "archetype": "Furtivo / Insano / Cósmico",
    "collection": "Invasão do Caos",
    "ct": 5,
    "attack": 8,
    "defense": 8,
    "description": "O CT deste combatente é reduzido em 4 caso um Herói com «Véu» em seu nome esteja em campo.\n\nApós 1 rodada em campo, adicione a sua mão, de qualquer lugar um combatente com «Floquinho» em seu nome, ela será tratado como Herói para outros efeitos de cartas.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736813176_Prancheta%20114.png?alt=media&token=5fc9b8a8-9682-4d32-a058-a333b8481913",
    "code": "2026/0001/00311",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "A SENHORA DO VÉU",
    "rarity": "Beta",
    "type": "Combatente",
    "archetype": "Véu / Cósmico",
    "collection": "Invasão do Caos",
    "ct": 12,
    "attack": 1,
    "defense": 1,
    "description": "O custo desta carta se torna 1 caso «Mahina - O Arauto do Véu» esteja em campo.\n\nCaso um Herói com «Véu» em seu nome seja enviado do seu lado campo para alguma Zona, descarte esta carta do seu campo e invoque de qualquer lugar a combatente «O Horror do Véu».",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736824516_Prancheta%20124.png?alt=media&token=ac326c55-91df-4613-b81c-14cc58939c93",
    "code": "2026/0001/00312",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "O HORROR DO VÉU",
    "rarity": "Beta",
    "type": "Combatente",
    "archetype": "Véu",
    "collection": "Invasão do Caos",
    "ct": 13,
    "attack": 0,
    "defense": 1,
    "description": "Este combatente só pode ser invocado pelo efeito de «A Senhora do Véu», ela é tratada como Herói para efeitos de cartas.\n\nEsta carta não é afetada por efeitos de cartas que a tenham como alvo, arquétipos inimigos não são aplicados nela e ela não pode ser eliminada em combate.\n\nEnquanto estiver em campo, nenhum combatente inimigo possui Arquétipo, cartas efeitos que ele usar custam o dobro de recursos e ele não pode usar equipamentos.\n\nNo começo da rodada, cause 10 de dano na Vida do Jogador Inimigo para cada Arquétipo diferente em campo.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736834438_Prancheta%20134.png?alt=media&token=cd014b01-db15-4fbf-903d-b7028a543934",
    "code": "2026/0001/00313",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Floquinho Caótica do Véu",
    "rarity": "Beta",
    "type": "Combatente",
    "archetype": "Véu / Caos / Ordem",
    "collection": "Invasão do Caos",
    "ct": 0,
    "attack": 1,
    "defense": 1,
    "description": "Para invocar esse combatente, gaste Vida de Jogador em vez de mana.\nEste combatente recebe 3 de CT, ataque e vida para cada ponto de Vida de Jogador gasto.\n\nSempre que este combatente causar dano a Vida do Jogador inimigo, aumente o custo das cartas dele em 2.\n\nEsse combatente remove o Arquétipo Macroversal dos Heróis inimigos enquanto estiver em campo.\n\nAo ser enviada do campo para alguma Zona, receba 5 Runas.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736844607_Prancheta%20144.png?alt=media&token=4b3634e9-a2ca-4cbe-9f88-9f87c5a37588",
    "code": "2026/0001/00314",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "APOTEOSE DO VÉU",
    "rarity": "Beta",
    "type": "Efeito",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 12,
    "attack": 0,
    "defense": 0,
    "description": "Esta carta permanece em campo e só pode ser negada por efeito de Heróis.\n\nQuando esta carta entrar em campo, invoque de qualquer lugar uma carta com «Camada» em eu nome.\n\nNo começo da Rodada, caso queira, perca 5 de Vida de Jogador e coloque em campo, de qualquer lugar uma carta com «Camada» em eu nome.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736861202_Prancheta%20154.png?alt=media&token=44b0ac14-0542-4565-a889-dbe7b2ced4a5",
    "code": "2026/0002/00315",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "AQUI FOI...",
    "rarity": "Beta",
    "type": "Efeito",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 6,
    "attack": 0,
    "defense": 0,
    "description": "Cause 3 de dano a todos os combatentes inimigos no campo para cada 1 de Vida de Jogador perdida (em relação a 20 de vida). Caso possua um combatente com «Floquinho Caótica» em seu nome do seu lado do campo, receba 3 Runas para cada combatente inimigo morto pelo efeito acima.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736875106_Prancheta%20164.png?alt=media&token=453be22c-a362-4040-8a82-b3b44e8010df",
    "code": "2026/0002/00316",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "CORAGEM AO CONTRÁRIO",
    "rarity": "Beta",
    "type": "Efeito",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 1,
    "attack": 0,
    "defense": 0,
    "description": "Negue o dano de um ataque recebido e perca 7 de Vida de Jogador.\n\nO efeito dessa carta não pode ser negada.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736884586_Prancheta%20174.png?alt=media&token=a7929aa6-d33b-4daa-947a-5ceea3504778",
    "code": "2026/0002/00317",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "O PAPAI CHEGOU",
    "rarity": "Beta",
    "type": "Efeito",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 1,
    "attack": 0,
    "defense": 0,
    "description": "O jogador com o combatente com maior custo em campo compra 5 cartas do topo de seu Deck.\n\nO jogador com o combatente com menor custo em campo, retorna 1 combatente de alguma Zona para o campo.\n\nCaso haja empate em qualquer um dos efeitos, esta carta não possui efeitos.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736893482_Prancheta%20184.png?alt=media&token=c5d55973-dc4a-44ad-b32b-45766b5107d8",
    "code": "2026/0002/00318",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Ritos do Festival",
    "rarity": "Beta",
    "type": "Efeito",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 5,
    "attack": 0,
    "defense": 0,
    "description": "Selecione 1 combatente do seu Deck (não Herói) e envie para a Zona Morta, após 2 rodadas, coloque ele em campo, esse combatente não pode sofrer efeitos de cartas na rodada em que é invocado.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736902648_Prancheta%20194.png?alt=media&token=5a6c5896-283e-432d-9ebe-4c9791b44f7d",
    "code": "2026/0002/00319",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Ato Final",
    "rarity": "Beta",
    "type": "Efeito",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 12,
    "attack": 0,
    "defense": 0,
    "description": "Envie seu Herói de qualquer lugar para alguma de suas Zonas e cause 5 de Dano Primordial no Deck inimigo. Caso o herói possua «Mahina» em seu nome, na rodada seguinte, envie ele de volta ao deck.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736910815_Prancheta%20204.png?alt=media&token=9548ccdd-b50a-45cc-a6fd-3b34becc4b9d",
    "code": "2026/0002/00320",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "CUMPLICIDADE",
    "rarity": "Beta",
    "type": "Efeito",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 1,
    "attack": 0,
    "defense": 0,
    "description": "Ambos os jogadores olham a mão um do outro, selecionam uma carta e descartam para a Zona Apagada, após isso, ambos selecionam uma carta de seus respectivos Decks e adicionam a mão. Se tiver uma carta com «Crystal» ou «Mahina» em seu nome do seu lado do campo, você seleciona duas cartas do seu Deck em vez de uma.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736920970_Prancheta%20214.png?alt=media&token=ac8abddd-872a-4c22-aa4d-6f0c42cfc024",
    "code": "2026/0002/00321",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "COMO PLANEJADO",
    "rarity": "Beta",
    "type": "Efeito",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 1,
    "attack": 0,
    "defense": 0,
    "description": "Negue uma carta usada e a envie para a Zona Apagada o do usuário, essa carta será usada automaticamente no começo da próxima rodada sem custo nenhum, caso não seja possível usar a carta, retorne ela para o Deck do usuário.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736929736_Prancheta%20224.png?alt=media&token=12d7138f-6b09-4bf2-ae86-4929fe86b1f9",
    "code": "2026/0002/00322",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "GOLPE NEFASTO",
    "rarity": "Beta",
    "type": "Efeito",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 2,
    "attack": 0,
    "defense": 0,
    "description": "Selecione um combatente da sua Zona Morta, ele ataca diretamente a vida de ambos os jogadores.\n\nEssa Carta não pode levar a vida dos jogadores a 0.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736938768_Prancheta%20234.png?alt=media&token=f97d9ea7-ae7d-4778-944b-cb882cd2f2a2",
    "code": "2026/0002/00323",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "PRIMEIRA CAMADA",
    "rarity": "Beta",
    "type": "Equipamento",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 1,
    "attack": 0,
    "defense": 0,
    "description": "Esta carta equipa o jogador e não um combatente específico.\n\nSeus combatentes recebem 1 de ataque para cada carta com «Camada» em seu nome do seu lado do campo.\n\nCombatentes com Arquétipo Véu recebem 3 de ataque ao invés de 1.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736948513_Prancheta%20244.png?alt=media&token=99414e69-0390-45ab-857d-ed4217dcc91d",
    "code": "2026/0002/00324",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "SEGUNDA CAMADA",
    "rarity": "Beta",
    "type": "Equipamento",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 2,
    "attack": 0,
    "defense": 0,
    "description": "Esta carta equipa o jogador e não um combatente específico.\n\nNo começo da rodada, caso queira, selecione um combatente inimigo em campo e tome controle dele, o CT desse combatente deve ser igual ou menor a quantidade de cartas com «Camada» em seu nome do seu lado do campo. Após o término da rodada, devolva o combatente de volta ao campo inimigo, o mesmo combatente não pode ser selecionado duas vezes.\n\nCom 2 ou mais combatentes com Arquétipo Véu do seu lado do campo, ao devolver o combatente para o jogador inimigo no efeito acima, cause 10 de dano ao combatente devolvido.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736959827_Prancheta%20254.png?alt=media&token=2e426911-23c5-4636-b123-786f6455608f",
    "code": "2026/0002/00325",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Terceira Camada",
    "rarity": "Beta",
    "type": "Equipamento",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 3,
    "attack": 0,
    "defense": 0,
    "description": "Esta carta equipa o jogador e não um combatente específico.\n\nReceba 1 de mana no começo da rodada para cada carta com «Camada» em seu nome do seu lado do campo.\n\nCom 2 ou mais combatentes com Arquétipo Véu do seu lado do campo, receba 2 de mana ao invés de 1 de mana.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736967768_Prancheta%20264.png?alt=media&token=358e1dea-f960-4e60-ba18-1997569005d7",
    "code": "2026/0002/00326",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Quarta Camada",
    "rarity": "Beta",
    "type": "Equipamento",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 4,
    "attack": 0,
    "defense": 0,
    "description": "Esta carta equipa o jogador e não um combatente específico. Receba 2 de Vida de Jogador no começo da rodada para cada carta com «Camada» em seu nome do seu lado do campo. Com 2 ou mais combatentes com Arquétipo Véu do seu lado do campo, receba 4 de Vida de Jogador ao invés de 2 de vida.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736976334_Prancheta%20274.png?alt=media&token=b04e4977-7f49-46fc-8903-fe63d78128c4",
    "code": "2026/0002/00327",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Quinta Camada",
    "rarity": "Beta",
    "type": "Equipamento",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 5,
    "attack": 0,
    "defense": 0,
    "description": "Esta carta equipa o jogador e não um combatente específico.\n\nReceba 1 runa no começo da rodada para cada carta com «Camada» em seu nome do seu lado do campo.\n\nCom 2 ou mais combatentes com Arquétipo Véu do seu lado do campo, uma vez por rodada, a qualquer momento, gaste 3 runas e negue uma carta a retornando pro Deck do dono.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736985818_Prancheta%20284.png?alt=media&token=266f0cd3-fe9a-4ddd-9ea6-66f06a069c2b",
    "code": "2026/0002/00328",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Sexta Camada",
    "rarity": "Beta",
    "type": "Equipamento",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 6,
    "attack": 0,
    "defense": 0,
    "description": "Esta carta equipa o jogador e não um combatente específico.\n\nEnquanto estiver em campo, reduz o CT de suas cartas em 1 para cada carta com «Camada» em seu nome do seu lado do campo.\n\nCom 2 ou mais combatentes com Arquétipo Véu do seu lado do campo, aumente em 1 o CT das cartas do jogador inimigo para cada carta com «Camada» em seu nome do seu lado do campo enquanto esta carta estiver em campo.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788736993902_Prancheta%20294.png?alt=media&token=5130354a-9c43-4d33-81c6-2f347b6b66d5",
    "code": "2026/0002/00329",
    "lore": "",
    "frame": "Moderno"
  },
  {
    "name": "Sétima Camada",
    "rarity": "Beta",
    "type": "Equipamento",
    "archetype": "Desconhecido",
    "collection": "Invasão do Caos",
    "ct": 7,
    "attack": 0,
    "defense": 0,
    "description": "Esta carta equipa o jogador e não um combatente específico.\n\nA qualquer momento, descarte 7 equipamentos do seu lado do campo com «Camada» em seu nome para a Zona Apagada, negue todas as cartas em campo e mão do jogador inimigo e as envie para a Zona Morta (sem ativar efeitos).\n\nCom 3 combatentes com Arquétipo Véu do seu lado do campo, cause 3 de dano na Vida do Jogador Inimigo e 3 de Dano Primordial no Deck dele para cada carta enviada a Zona Morta no efeito acima.",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/gen-lang-client-0120804533.firebasestorage.app/o/wb_images%2F1788737003866_Prancheta%20304.png?alt=media&token=619a40a6-98a9-4b46-b06d-45d2479f7ef2",
    "code": "2026/0002/00330",
    "lore": "",
    "frame": "Moderno"
  }
];
